services:
  - type: web
    name: helmet-detection-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "waitress-serve --port=$PORT app:app"
    plan: free
    envVars:
      FLASK_ENV: production
